--
-- Script was generated by Devart dbForge Data Generator for Oracle, Version 2.2.15.0
-- Product Home Page: http://www.devart.com/dbforge/oracle/data-generator
-- Script date 3/22/2021 4:12:10 PM
-- Target server version: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Target connection string: User Id=IWISH;Unicode=True;Connection Timeout=0;Direct=True;Service Name=XE
--


SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+02:00';
--
-- Delete data from the table 'IWISH.ITEM'
--
DELETE FROM IWISH.ITEM;

--
-- Inserting data into table IWISH.ITEM
--
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21090, N'Air_Fryer', 1589, N'Dolor sed enim. Quia minima error! Ad;', 18);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21091, N'Flip_Flop', 1937, N'Quam delectus aut. Esse sed beatae.', 14);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21092, N'Moisure', 939, N'Dolor iste unde. Vitae et odit! Ipsa.', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21093, N'Mirror', 2386, N'Omnis dignissimos minima iste sed.', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21094, N'Umbrella', 3000, N'Rerum quas provident; aspernatur omnis.', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21095, N'Perfumes', 2536, N'Ut eum dolorem. Voluptatum unde.', 8);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21096, N'Knives', 947, N'Eos cum explicabo. Incidunt ut odit!', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21097, N'Lipstick', 2173, N'Ipsam distinctio ad. Reprehenderit;', 19);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21098, N'Gloss', 1338, N'Sit unde error. Aliquid dolore ullam.', 6);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21099, N'Maker', 2528, N'Officia ullam voluptatem. Ducimus.', 8);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21100, N'Curtain', 581, N'Veniam culpa dolor voluptas voluptatem.', 10);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21101, N'Juice_Maker', 1581, N'Repudiandae soluta voluptates. Vero.', 9);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21102, N'Eyebrow_Gel', 922, N'Et voluptas natus. Facilis sed quia.', 3);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21103, N'Blusher', 804, N'Quos iste praesentium. Quaerat quia?', 3);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21104, N'Spray', 2396, N'Sint ducimus quia. Laudantium et!', 17);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21105, N'SweetPants', 2158, N'Dolor sed quo. Sequi qui dolore. Qui?', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21106, N'Brush', 2767, N'Voluptatem odio qui a aut.', 15);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21107, N'Food_Containers', 2816, N'Ut ea sapiente eligendi.', 15);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21108, N'Salads_Plate', 1328, N'Dolorum libero blanditiis adipisci ut.', 7);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21109, N'Set', 2302, N'Laudantium libero totam; iste optio.', 4);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21110, N'Bronzer', NULL, NULL, NULL);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21111, N'Hanger', 2648, N'Nobis aut voluptatibus. Quisquam.', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21112, N'Eyeliner', 2498, N'Ut fugiat labore. Ea error officia.', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21113, N'Blanket', 1037, N'Numquam doloribus et; aut consequuntur.', 6);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21114, N'Pasta', 1236, N'Eius eaque voluptatem facere labore...', 11);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21115, N'Bowder', 1248, N'Eligendi consequatur sint.', 3);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21116, N'Camera', 2757, N'Ipsam quasi veritatis. Dicta autem et.', 6);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21117, N'Cat_toy', 1334, N'Incidunt molestias unde. Sapiente unde.', 12);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21118, N'Scarf', 1124, N'Porro numquam sed. Quaerat veniam!', 18);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21119, N'Jewelery_Box', 724, N'Id tempora corrupti. Voluptatem sunt.', 15);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21120, N'Salad_Maker', 1215, N'Et laborum quia. Corporis et at.', 4);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21121, N'Conselar', 2119, N'Non corporis nisi. Dolores debitis.', 17);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21122, N'Foundation', 1153, N'Perferendis saepe voluptatem. Id.', 14);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21123, N'Laptop_Sleeves', 2297, N'Voluptatum voluptates voluptate.', 12);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21124, N'Washer', 2092, N'Et ullam voluptatem. Voluptas labore?', 9);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21125, N'Loreal', 651, N'Unde veniam nulla. Doloremque ut;', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21126, N'Lipliner', 1738, N'Voluptatem quaerat expedita. Vitae?', 19);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21127, N'Mobile_Case', 1137, N'Sit aut hic. Ducimus laboriosam in?', 15);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21128, N'Mask', 1121, N'Voluptatem numquam consectetur. Quas.', 7);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21129, N'Mascara', 1951, N'Impedit unde sit. Eum aut nam.', 7);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21130, N'Highlighter', 534, N'Consequatur expedita excepturi. Quo et?', 5);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21131, N'Cake_Maker', 2697, N'Ut consequatur ducimus. Corrupti;', 17);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21132, N'Body_oil', 1899, N'Sed est iste. Consequatur ullam.', 3);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21133, N'Contour', NULL, NULL, NULL);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21134, N'Keys_Hanger', 2146, N'Doloremque id aut. Amet dolor iste.', 11);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21135, N'Sweetshirt', 1103, N'Sunt saepe rem. Hic perspiciatis et;', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21136, N'Sun_Screen', 1111, N'Ducimus rerum qui. Consequatur quo;', 12);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21137, N'Eyeshadow', 1119, N'Aut ducimus sed; similique delectus.', 5);

COMMIT;