--
-- Script was generated by Devart dbForge Data Generator for Oracle, Version 2.2.15.0
-- Product Home Page: http://www.devart.com/dbforge/oracle/data-generator
-- Script date 3/22/2021 3:38:30 PM
-- Target server version: Oracle Database 11g Express Edition Release 11.2.0.2.0 - Production
-- Target connection string: User Id=IWISH;Unicode=True;Connection Timeout=0;Direct=True;Service Name=XE
--


SET SQLBLANKLINES ON;
SET DEFINE OFF;
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+02:00';
--
-- Delete data from the table 'IWISH.ITEM'
--
DELETE FROM IWISH.ITEM;

--
-- Inserting data into table IWISH.ITEM
--
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21041, '', 1589, N'Dolor sed enim. Quia minima error! Ad;', 18);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21042, N'Scarf.', 1937, N'Quam delectus aut. Esse sed beatae.', 14);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21043, N'Shorts.', 939, N'Dolor iste unde. Vitae et odit! Ipsa.', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21044, N'Hat.', 2386, N'Omnis dignissimos minima iste sed.', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21045, N'Curtain.', 3000, N'Rerum quas provident; aspernatur omnis.', 13);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21046, N'Earpods.', 2536, N'Ut eum dolorem. Voluptatum unde.', 8);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21047, N'Tshirt.', 947, N'Eos cum explicabo. Incidunt ut odit!', 20);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21048, N'Bag...', 2173, N'Ipsam distinctio ad. Reprehenderit;', 19);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21049, N'Bowder.', 1338, N'Sit unde error. Aliquid dolore ullam.', 6);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21050, N'Screen.', 2528, N'Officia ullam voluptatem. Ducimus.', 8);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21051, N'Plates.', 581, N'Veniam culpa dolor voluptas voluptatem.', 10);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21052, N'Ipod.', 1581, N'Repudiandae soluta voluptates. Vero.', 9);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21053, N'Laptop.', 922, N'Et voluptas natus. Facilis sed quia.', 3);
INSERT INTO IWISH.ITEM(ID, NAME, PRICE, DESCRIPTION, QUANTITY) VALUES
(21054, N'Contour.', 804, N'Quos iste praesentium. Quaerat quia?', 3);

COMMIT;