/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lazerd;

import java.awt.CardLayout;

/**
 *
 * @author norha
 */
public class JFrame extends javax.swing.JFrame {
CardLayout cd;
 int counter = 0;
    /**
     * Creates new form JFrame
     */
    public JFrame() {
        initComponents();
        cd = new CardLayout();
        P2.setLayout(cd);
        P2.add("1",FirstPanel);
        P2.add("2",SecondPanel);
        P2.add("3",ThirdPanel);
        P2.add("4",LastPanel);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstPanel = new javax.swing.JPanel();
        FirstLabel = new javax.swing.JLabel();
        SecondPanel = new javax.swing.JPanel();
        SecondLabel = new javax.swing.JLabel();
        ThirdPanel = new javax.swing.JPanel();
        ThirdLabel = new javax.swing.JLabel();
        LastPanel = new javax.swing.JPanel();
        LastLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        First = new javax.swing.JButton();
        Last = new javax.swing.JButton();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Choose = new javax.swing.JComboBox<>();
        P2 = new javax.swing.JPanel();

        FirstLabel.setText("First");

        javax.swing.GroupLayout FirstPanelLayout = new javax.swing.GroupLayout(FirstPanel);
        FirstPanel.setLayout(FirstPanelLayout);
        FirstPanelLayout.setHorizontalGroup(
            FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FirstPanelLayout.setVerticalGroup(
            FirstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FirstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SecondLabel.setText("Second");

        javax.swing.GroupLayout SecondPanelLayout = new javax.swing.GroupLayout(SecondPanel);
        SecondPanel.setLayout(SecondPanelLayout);
        SecondPanelLayout.setHorizontalGroup(
            SecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(SecondLabel)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        SecondPanelLayout.setVerticalGroup(
            SecondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SecondPanelLayout.createSequentialGroup()
                .addComponent(SecondLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        ThirdLabel.setText("Third");

        javax.swing.GroupLayout ThirdPanelLayout = new javax.swing.GroupLayout(ThirdPanel);
        ThirdPanel.setLayout(ThirdPanelLayout);
        ThirdPanelLayout.setHorizontalGroup(
            ThirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ThirdLabel)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        ThirdPanelLayout.setVerticalGroup(
            ThirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ThirdPanelLayout.createSequentialGroup()
                .addComponent(ThirdLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        LastLabel.setText("Last");

        javax.swing.GroupLayout LastPanelLayout = new javax.swing.GroupLayout(LastPanel);
        LastPanel.setLayout(LastPanelLayout);
        LastPanelLayout.setHorizontalGroup(
            LastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LastLabel)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        LastPanelLayout.setVerticalGroup(
            LastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LastPanelLayout.createSequentialGroup()
                .addComponent(LastLabel)
                .addGap(0, 86, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        First.setText("First");
        First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstActionPerformed(evt);
            }
        });

        Last.setText("Last");
        Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastActionPerformed(evt);
            }
        });

        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Choose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        Choose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(Previous)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Next)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(First)
                .addGap(4, 4, 4)
                .addComponent(Last)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(First)
                    .addComponent(Last)
                    .addComponent(Next)
                    .addComponent(Previous)
                    .addComponent(Choose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        P2.setLayout(new java.awt.CardLayout());
        getContentPane().add(P2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
        cd.next(P2);
        
        if(counter < Choose.getItemCount()-1){ 
            Choose.setSelectedIndex(++counter);
        }
        else{ 
            counter = 0;
            Choose.setSelectedIndex(counter);
        }
        
        
        
    }//GEN-LAST:event_NextActionPerformed

    private void FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstActionPerformed
        // TOD add your handling code here:
        cd.first(P2);
        counter = 0;
        Choose.setSelectedIndex(counter);
        
    }//GEN-LAST:event_FirstActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
        cd.previous(P2);
        
        if(counter > 0){ 
            Choose.setSelectedIndex(--counter);
        }

        else{ 
            counter = 0;
            Choose.setSelectedIndex(Choose.getItemCount()-1);
            counter= Choose.getItemCount()-1;
        }
        //Choose.setSelectedIndex(Choose.getSelectedIndex()-1);
        
    }//GEN-LAST:event_PreviousActionPerformed

    private void LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastActionPerformed
        // TODO add your handling code here:
        cd.last(P2);
        counter = Choose.getItemCount()-1;
        Choose.setSelectedIndex(counter);
        
    }//GEN-LAST:event_LastActionPerformed

    private void ChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseActionPerformed
        // TODO add your handling code here:
        String x = Choose.getSelectedItem().toString();
        cd.show(P2,x);
        counter = Choose.getSelectedIndex();
  
    }//GEN-LAST:event_ChooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Choose;
    private javax.swing.JButton First;
    private javax.swing.JLabel FirstLabel;
    private javax.swing.JPanel FirstPanel;
    private javax.swing.JButton Last;
    private javax.swing.JLabel LastLabel;
    private javax.swing.JPanel LastPanel;
    private javax.swing.JButton Next;
    private javax.swing.JPanel P2;
    private javax.swing.JButton Previous;
    private javax.swing.JLabel SecondLabel;
    private javax.swing.JPanel SecondPanel;
    private javax.swing.JLabel ThirdLabel;
    private javax.swing.JPanel ThirdPanel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
