/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import oracle.jdbc.driver.* ;
import java.sql.* ;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author norha
 */
public class DB_interface extends javax.swing.JFrame {
    Connection con;
    ResultSet rs;
    Boolean flg=true;
    Boolean flg2=true;
    String id;
    String vid;
    String vfname;
    String vmname;
    String vlname;
    String vemail;
    String vphone;

    /**
     * Creates new form DB_interface
     */
    public DB_interface() {
        try {
            initComponents();
            DriverManager.registerDriver(new OracleDriver());
            /*
            after creating your schema run this sql command : 
            CREATE TABLE EMPX(EMPLOYEE_ID varchar(25),FIRST_NAME varchar(25),MIDDLE_NAME  varchar(25),LAST_NAME varchar(25),EMAIL varchar(55),PHONE_NUMBER varchar(25));
            INSERT INTO EMPX VALUES ('121','JOHN','WILL','SMITH','jsmith@ex.com','5552493');*/
            con = DriverManager.getConnection("jdbc:oracle:thin:@127.0.0.1:1521:xe","nour","nour");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select * from EMPX order by EMPLOYEE_ID");
            rs.first();
            txtid.setText(rs.getString("EMPLOYEE_ID"));
            txtfname.setText(rs.getString("FIRST_NAME"));
            txtmname.setText(rs.getString("MIDDLE_NAME"));
            txtlname.setText(rs.getString("LAST_NAME"));
            txtemail.setText(rs.getString("EMAIL"));
            txtphone.setText(rs.getString("PHONE_NUMBER"));
            txtid.setEditable(false);
            txtfname.setEditable(false);
            txtmname.setEditable(false);
            txtlname.setEditable(false);
            txtemail.setEditable(false);
            txtphone.setEditable(false);
            

        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtmname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        btnnew = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnfirst = new javax.swing.JButton();
        btnprev = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnlast = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Middle Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Email");

        jLabel6.setText("Phone");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        txtmname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmnameActionPerformed(evt);
            }
        });

        txtlname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlnameActionPerformed(evt);
            }
        });

        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });

        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnfirst.setText("First");
        btnfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstActionPerformed(evt);
            }
        });

        btnprev.setText("Previous");
        btnprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprevActionPerformed(evt);
            }
        });

        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnlast.setText("Last");
        btnlast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlastActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfname, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(txtmname)
                            .addComponent(txtlname)
                            .addComponent(txtemail)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnnew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnfirst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnprev)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnnext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnlast))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtmname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnnew)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnfirst)
                    .addComponent(btnlast)
                    .addComponent(btnnext)
                    .addComponent(btnprev))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
            if(flg==true) {
            txtid.setText("");
            txtfname.setText("");
            txtmname.setText("");
            txtlname.setText("");
            txtemail.setText("");
            txtphone.setText("");
            btnnew.setText("Save");
            flg = false;
            txtid.setEditable(true);
            txtfname.setEditable(true);
            txtmname.setEditable(true);
            txtlname.setEditable(true);
            txtemail.setEditable(true);
            txtphone.setEditable(true);
            }
            else{
                try {
                    btnnew.setText("New");
                    vid = txtid.getText();
                    vfname = txtfname.getText();
                    vmname = txtmname.getText();
                    vlname = txtmname.getText();
                    vemail = txtemail.getText();
                    vphone = txtphone.getText();
                    PreparedStatement pst = con.prepareStatement("INSERT INTO EMPX VALUES(?,?,?,?,?,?)");
                    pst.setString (1, vid);
                    pst.setString (2, vfname);
                    pst.setString(3, vmname);
                    pst.setString(4, vlname);
                    pst.setString(5, vemail);
                    pst.setString(6, vphone);
                    ResultSet prs = pst.executeQuery();
                    con.commit();
                                txtid.setEditable(false);
            txtfname.setEditable(false);
            txtmname.setEditable(false);
            txtlname.setEditable(false);
            txtemail.setEditable(false);
            txtphone.setEditable(false);
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select * from EMPX order by EMPLOYEE_ID");
                    flg = true;
                } 
                catch (SQLException ex) {
                    Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
    }//GEN-LAST:event_btnnewActionPerformed

    private void txtmnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmnameActionPerformed

    private void txtlnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlnameActionPerformed

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        try {
            if(rs.next()) {
                txtid.setText(rs.getString("EMPLOYEE_ID"));
                txtfname.setText(rs.getString("FIRST_NAME"));
                txtmname.setText(rs.getString("MIDDLE_NAME"));
                txtlname.setText(rs.getString("LAST_NAME"));
                txtemail.setText(rs.getString("EMAIL"));
                txtphone.setText(rs.getString("PHONE_NUMBER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void btnprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprevActionPerformed
         try {
            if(rs.previous()) {
                txtid.setText(rs.getString("EMPLOYEE_ID"));
                txtfname.setText(rs.getString("FIRST_NAME"));
                txtmname.setText(rs.getString("MIDDLE_NAME"));
                txtlname.setText(rs.getString("LAST_NAME"));
                txtemail.setText(rs.getString("EMAIL"));
                txtphone.setText(rs.getString("PHONE_NUMBER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnprevActionPerformed

    private void btnfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstActionPerformed
         try {
            if(rs.first()) {
                txtid.setText(rs.getString("EMPLOYEE_ID"));
                txtfname.setText(rs.getString("FIRST_NAME"));
                txtmname.setText(rs.getString("MIDDLE_NAME"));
                txtlname.setText(rs.getString("LAST_NAME"));
                txtemail.setText(rs.getString("EMAIL"));
                txtphone.setText(rs.getString("PHONE_NUMBER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnfirstActionPerformed

    private void btnlastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlastActionPerformed
         try {
            if(rs.last()) {
                txtid.setText(rs.getString("EMPLOYEE_ID"));
                txtfname.setText(rs.getString("FIRST_NAME"));
                txtmname.setText(rs.getString("MIDDLE_NAME"));
                txtlname.setText(rs.getString("LAST_NAME"));
                txtemail.setText(rs.getString("EMAIL"));
                txtphone.setText(rs.getString("PHONE_NUMBER"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnlastActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        if(flg2==true) {
            btnupdate.setText("Save");
            flg2 = false;
            id = txtid.getText();
            txtid.setEditable(true);
            txtfname.setEditable(true);
            txtmname.setEditable(true);
            txtlname.setEditable(true);
            txtemail.setEditable(true);
            txtphone.setEditable(true);
            
            }
            else{
                try {
                    btnupdate.setText("Update");
                    vid = txtid.getText();
                    vfname = txtfname.getText();
                    vmname = txtmname.getText();
                    vlname = txtmname.getText();
                    vemail = txtemail.getText();
                    vphone = txtphone.getText();
                    PreparedStatement pst2 = con.prepareStatement("UPDATE EMPX SET EMPLOYEE_ID = ?,FIRST_NAME = ?,MIDDLE_NAME = ?, LAST_NAME = ?,EMAIL = ?, PHONE_NUMBER=? WHERE EMPLOYEE_ID=?");
                    pst2.setString (1, vid);
                    pst2.setString (2, vfname);
                    pst2.setString(3, vmname);
                    pst2.setString(4, vlname);
                    pst2.setString(5, vemail);
                    pst2.setString(6, vphone);
                    pst2.setString(7, id);
                    int prs2 = pst2.executeUpdate();
                    con.commit();
                    txtid.setEditable(false);
                    txtfname.setEditable(false);
                    txtmname.setEditable(false);
                    txtlname.setEditable(false);
                    txtemail.setEditable(false);
                    txtphone.setEditable(false);
                    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
                    rs = st.executeQuery("select * from EMPX order by EMPLOYEE_ID");
                    flg2 = true;
                } 
                catch (SQLException ex) {
                    Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            vid = txtid.getText();
            txtid.setText("");
            txtfname.setText("");
            txtmname.setText("");
            txtlname.setText("");
            txtemail.setText("");
            txtphone.setText("");
            PreparedStatement pst3 = con.prepareStatement("DELETE FROM EMPX WHERE EMPLOYEE_ID=?");
            pst3.setString (1, vid);
            ResultSet prs = pst3.executeQuery();
            con.commit();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery("select * from EMPX order by EMPLOYEE_ID");
        } catch (SQLException ex) {
            Logger.getLogger(DB_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DB_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DB_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DB_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DB_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DB_interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnfirst;
    private javax.swing.JButton btnlast;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprev;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtphone;
    // End of variables declaration//GEN-END:variables
}
